### ISSUE TITLE
Integrate New TF Model 

### ISSUE THREAD

**Issue by bearprada** [plant-tw/PlantsCam-Android#4]
*Waiting* for the new TF Model from @fumin

**Comment by fumin** [comment]
A first prototype will be delivered by @x4base , looping him here.

**Comment by bearprada** [comment]
copied from Messenger : @x4base 

URL : 
https://s3.console.aws.amazon.com/s3/buckets/nandalu-plant/resnet_v2_50_plants_non_exif/?region=us-east-1&tab=overview

input的影像前處理是
1. 維持長寬比resize到最小邊長為224
2. 在正中央crop到正方型
3. RGB channel分別減掉以下的值
     _R_MEAN = 123.68
    _G_MEAN = 116.78
    _B_MEAN = 103.94

input_tensor_name = "input:0"
output_tensor_name = "resnet_v2_50/predictions/Reshape_1:0"
出來會是每個label的probability
還有一個labels.txt　是用來對照每個label的名字的

**Comment by bearprada** [comment]
I will change this issue to another name because the model from @x4base might not need the Gyro information.

**Comment by bearprada** [comment]
crash log : 

```
java.lang.RuntimeException: Failed to load model from 'file:///android_asset/frozen_graph.pb'
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
  at android.app.ActivityThread.-wrap14(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6692)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: resnet_v2_50/conv1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](resnet_v2_50/Pad, resnet_v2_50/conv1/weights/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:392)
  at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
  at plantscam.android.prada.lab.plantscamera.PlantFreezeClassifier2.<init>(PlantFreezeClassifier2.kt:16) 
  at plantscam.android.prada.lab.plantscamera.MainActivity.onCreate(MainActivity.kt:25) 
  at android.app.Activity.performCreate(Activity.java:6912) 
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877) 
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
  at android.app.ActivityThread.-wrap14(ActivityThread.java) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
  at android.os.Handler.dispatchMessage(Handler.java:102) 
  at android.os.Looper.loop(Looper.java:154) 
  at android.app.ActivityThread.main(ActivityThread.java:6692) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

tag @x4base

**Comment by bearprada** [comment]
upgrade to tensorflow android v1.8.0. it still crash

```
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: resnet_v2_50/conv1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](resnet_v2_50/Pad, resnet_v2_50/conv1/weights/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
                                                                                              at org.tensorflow.contrib.android.TensorFlowInferenceInterface.loadGraph(TensorFlowInferenceInterface.java:392)
                                                                                              at org.tensorflow.contrib.android.TensorFlowInferenceInterface.<init>(TensorFlowInferenceInterface.java:96)
                                                                                              at plantscam.android.prada.lab.plantscamera.PlantFreezeClassifier2.<init>(PlantFreezeClassifier2.kt:16) 
                                                                                              at plantscam.android.prada.lab.plantscamera.MainActivity.onCreate(MainActivity.kt:25) 
```

**Comment by bearprada** [comment]
after clean project, we solve the model issue 👎

**Comment by x4base** [comment]
You can refer to this file for the workflow: https://github.com/plant-tw/models_plant/blob/9a3d0cd2d5c1af7481875d695c4f96f9f132ced1/research/slim/eval_lib.py .
See the functions run_inference_by_pb, _inference_by_pb, and pre_process

**Comment by bearprada** [comment]
Copy from FB messenger 

https://drive.google.com/drive/folders/11qHwwIidbO6cXh5aOUIMrd3QslE_HaIQ
上傳了mobilenet的model for android/ios, preprocess圖片的方法跟resnet不太一樣　可以參考 https://github.com/plant-tw/models_plant/blob/427bea9f5242ecc513b894fc8c458a8acd88ccd4/research/slim/eval_lib.py 的pre_process_mobilenet

步驟：
1. 把長寬都crop到剩原本的0.875倍 (central crop)
2. resize到 224x224
3. 每個pixel 作以下運算: x' = ((x /255) - 0.5) * 2
output 是 `MobilenetV1/Predictions/Reshape_1`

**Comment by bearprada** [comment]
it's done https://github.com/plant-tw/PlantsCam-Android/commit/eb165d8457b37b0ac835039874864b392b09438c
